version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce_analysis_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./scripts/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5